### ISSUE TITLE
Some files don't have right extension

### ISSUE THREAD

**Issue by jai-dewani** [utkarsh-raj/snippets#11]
- [Codechef_BINIM2](https://github.com/utkarsh-raj/snippets/blob/master/codechef_BINIM2)
- [codechef_RECTANGL](https://github.com/utkarsh-raj/snippets/blob/master/codechef_RECTANGL)
- [codeshef_ADASTAIR](https://github.com/utkarsh-raj/snippets/blob/master/codeshef_ADASTAIR)

**Comment by utkarsh-raj** [comment]
If the issue is still open, should you be assigned to it @jai-dewani ?

**Comment by jai-dewani** [comment]
The issue has been addressed in #14  
- [x] Successfully merged into master branch

**Comment by jai-dewani** [comment]
Next set of files which require correct extensions:
- [ ] [Codechef_EID](https://github.com/utkarsh-raj/snippets/blob/master/codechef_EID)
- [ ] [Codechef_PROBSET](https://github.com/utkarsh-raj/snippets/blob/master/codechef_PROBSET)
- [ ] [codechef_START01](https://github.com/utkarsh-raj/snippets/blob/master/codechef_START01)

**Comment by utkarsh-raj** [comment]
Can you please raise a new issue so that new volunteers can be try the fixes @jai-dewani ?
